server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.232.129/spring_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 120197
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.232.129
    port: 6379
#    database: 0

logging:
  level:
    com:
      zhangjie: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
